title: 황용대와 고이선의 결혼식에 초대합니다
email: stadia@gmail.com
url: "http://180617.ga" # the base hostname & protocol for your site, e.g. http://example.com
github_username: stadia
name: 황용대와 고이선의 결혼식에 초대합니다

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
    - _assets/fonts
    - _assets/images
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
  gzip: true
  cdn:
    destination: false
    url: http://cdn.180617.ga

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock

plugins:
  - jekyll-assets
  - jekyll-sitemap

permalink: pretty

collections:
  sections:
    output: false
